library(car)
library(datasets)
attach(mtcars)
library(dplyr)
library(GGally)
library(ggplot2)
library(graphics)
library(grDevices)
library(knitr)
library(kernlab)
library(magrittr)
library(MASS)
library(xtable)

